project_id = "ngbpmludrnwmkwzsdasp"

[functions.send-ticket-email]
verify_jwt = false

[functions.validate-qr-code]
verify_jwt = false

[functions.create-stripe-payment]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false