project_id = "ngbpmludrnwmkwzsdasp"

[functions.send-ticket-email]
verify_jwt = false

[functions.validate-qr-code]
verify_jwt = false

[functions.hubla-webhook]
verify_jwt = false

[functions.create-hubla-payment]
verify_jwt = true