// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ngbpmludrnwmkwzsdasp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5nYnBtbHVkcm53bWt3enNkYXNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzNjA4MTgsImV4cCI6MjA2NDkzNjgxOH0.0wyBoC4VePpbRHRWlFDFKbmnK5ty8tWSjoS7x-0v_uk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);